package com.tindpt;

public enum Field {
    HVT, SINHNGAY, SINHTHANG, SINHNAM, FULLSINH, NOISINH,
    CMND, NGAYCAP, THANGCAP, NAMCAP, NGAYCAPFULL, CAPTAI,
    THUONGTRU, AP, XA, HUYEN, TINH, DANTOC, TONGIAO, TRINHDO,
    TENCHA, TUOICHA, NGHECHA, HIENOCHA, TENME, TUOIME, NGHEME, HIENOME,
    AC1, AC2, AC3, NGHEAC, HIENOAC, NGAYKI, THANGKI, NAMKI
}
